import localFont from 'next/font/local' 
const myFont = localFont({
  src: '../../fonts/NotoSans-Regular.ttf',
})

import "./globals.css";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={myFont.className}>
      <body>
        {children}
      </body>
    </html>
  );
}
